# Generated by Django 3.1.12 on 2025-01-04 18:49

import api.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('message', models.CharField(help_text='Enter the banner message', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Check to display the banner')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Live Classes', 'Live Classes'), ('Self-Paced', 'Self-Paced')], default='self_paced', max_length=20)),
                ('course_type', models.CharField(choices=[('university', 'University Course'), ('job', 'Job-Oriented Course')], default='university', max_length=20)),
                ('learn', djongo.models.fields.ArrayField(blank=True, model_container=api.models.Learn, null=True)),
                ('skills', djongo.models.fields.ArrayField(blank=True, model_container=api.models.Skill, null=True)),
                ('time_need', models.IntegerField(default=24)),
                ('review', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('price', models.IntegerField()),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('Semester_num', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('learn', djongo.models.fields.ArrayField(blank=True, model_container=api.models.Learn, null=True)),
                ('skills', djongo.models.fields.ArrayField(blank=True, model_container=api.models.Skill, null=True)),
                ('time_need', models.IntegerField(default=24)),
                ('review', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('price', models.IntegerField()),
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='api.course')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'unique_together': {('course', 'Semester_num')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('sub_id', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('image', models.BinaryField(blank=True, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.semester')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('videoUrl', models.URLField()),
                ('driveLink', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videoss', to='api.subject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('subject_id', djongo.models.fields.ArrayField(blank=True, model_container=api.models.Sub, null=True)),
                ('viewed_videos', models.ManyToManyField(blank=True, to='api.Videos')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
